#pragma once

enum AttackType {
	ATTACKTYPE_UDP1,
	ATTACKTYPE_UDP2,
	ATTACKTYPE_UDP3,
	ATTACKTYPE_UDP4,
	ATTACKTYPE_UDP5,
	ATTACKTYPE_VGBOOT,
	ATTACKTYPE_GOTT,
	ATTACKTYPE_NYTRO,
	ATTACKTYPE_SLOWLORIS,
	ATTACKTYPE_
}